version: "3.9"
services:
  mongo:
    image: mvertes/alpine-mongo
    container_name: mongo-clothes
    ports:
      - '27017:27017'
    networks:
      - server
networks:
  server:
    driver: bridge

volumes:
  data:
    driver: local
