version: "3.9"
services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./fullchainkey.pem:/etc/ssl/cert.pem
      - ./primarykey.pem:/etc/ssl/key.pem
    restart: unless-stopped
    networks:
      - server
  server:
    build:
      context: ./server
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '5000:5000'
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: mongoose
    env_file: common.env
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - server
    links:
      - mongo
    depends_on:
      - mongo
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./client:/app
      - /app/node_modules/
    command: npm start
  mongo:
    image: mvertes/alpine-mongo
    container_name: mongo-clothes
    ports:
      - '27017:27017'
    networks:
      - server
networks:
  server:
    driver: bridge

volumes:
  data:
    driver: local
